# Generated by Django 5.2.15 on 2026-07-03 18:58

from django.db import migrations


SERVICES = [
    ("Consultation", "CONS", 5000),
    ("Full Blood Count", "FBC", 3500),
    ("Malaria RDT", "MRDT", 2000),
    ("HIV Rapid Test", "HIV", 1500),
    ("Chest X-Ray", "CXR", 8000),
    ("Ultrasound", "US", 12000),
    ("Pharmacy Dispensing Fee", "RX", 1000),
    ("Admission Bed-Day", "BED", 15000),
    ("Outpatient Procedure", "PROC", 10000),
]


def seed_catalog(apps, schema_editor):
    ServiceCatalogItem = apps.get_model("billing", "ServiceCatalogItem")
    for name, code, price in SERVICES:
        ServiceCatalogItem.objects.get_or_create(code=code, defaults={"name": name, "price_mwk": price})


def reverse_catalog(apps, schema_editor):
    ServiceCatalogItem = apps.get_model("billing", "ServiceCatalogItem")
    ServiceCatalogItem.objects.filter(code__in=[code for _, code, _ in SERVICES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_catalog, reverse_catalog),
    ]
