# Generated by Django 5.2.15 on 2026-07-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0002_fluidbalanceentry_historicalfluidbalanceentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='cause_of_death',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='admission',
            name='death_certificate_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaladmission',
            name='cause_of_death',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='historicaladmission',
            name='death_certificate_issued',
            field=models.BooleanField(default=False),
        ),
    ]
