# Generated by Django 5.2.15 on 2026-07-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='icd_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='encounter',
            name='icd_display',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalencounter',
            name='icd_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='historicalencounter',
            name='icd_display',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
