# Generated by Django 5.2.15 on 2026-07-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_add_stocklevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='contraindicated_in_breastfeeding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drug',
            name='interacting_drugs',
            field=models.ManyToManyField(blank=True, to='pharmacy.drug'),
        ),
    ]
