# Generated by Django 5.2.15 on 2026-07-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_drug_contraindicated_in_breastfeeding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprescription',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
