# Generated by Django 5.2.15 on 2026-07-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevent',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
