# Generated by Django 5.2.15 on 2026-07-03 21:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTriageEncounter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('triage_category', models.CharField(choices=[('immediate', 'Immediate (Resuscitation)'), ('emergency', 'Emergency'), ('urgent', 'Urgent'), ('standard', 'Standard'), ('non_urgent', 'Non-Urgent')], max_length=20)),
                ('presenting_condition', models.TextField()),
                ('outcome', models.CharField(blank=True, choices=[('discharged', 'Discharged'), ('admitted', 'Admitted'), ('referred', 'Referred'), ('dead', 'Dead')], max_length=20, null=True)),
                ('disposition_note', models.TextField(blank=True)),
                ('rapid_registration', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient')),
                ('triaged_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical triage encounter',
                'verbose_name_plural': 'historical triage encounters',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TriageEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triage_category', models.CharField(choices=[('immediate', 'Immediate (Resuscitation)'), ('emergency', 'Emergency'), ('urgent', 'Urgent'), ('standard', 'Standard'), ('non_urgent', 'Non-Urgent')], max_length=20)),
                ('presenting_condition', models.TextField()),
                ('outcome', models.CharField(blank=True, choices=[('discharged', 'Discharged'), ('admitted', 'Admitted'), ('referred', 'Referred'), ('dead', 'Dead')], max_length=20, null=True)),
                ('disposition_note', models.TextField(blank=True)),
                ('rapid_registration', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_encounters', to='patients.patient')),
                ('triaged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_encounters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
