# Generated by Django 5.2.15 on 2026-07-02 09:56

import core.encrypted_fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPatient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('patient_number', models.CharField(db_index=True, editable=False, max_length=20)),
                ('national_id', core.encrypted_fields.EncryptedCharField(blank=True, max_length=64)),
                ('national_id_lookup', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=150)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age_estimated', models.BooleanField(default=False)),
                ('phone_number', core.encrypted_fields.EncryptedCharField(blank=True, max_length=32)),
                ('phone_number_lookup', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('village', models.CharField(blank=True, max_length=150)),
                ('traditional_authority', models.CharField(blank=True, max_length=150)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, choices=[('northern', 'Northern'), ('central', 'Central'), ('southern', 'Southern')], max_length=10)),
                ('occupation_or_school', models.CharField(blank=True, max_length=150)),
                ('patient_category', models.CharField(choices=[('outpatient', 'Outpatient'), ('inpatient', 'Inpatient'), ('student', 'Student'), ('staff', 'Staff'), ('private', 'Private'), ('referred', 'Referred'), ('emergency', 'Emergency'), ('research', 'Research participant')], default='outpatient', max_length=20)),
                ('consent_care', models.BooleanField(default=True)),
                ('consent_teaching', models.BooleanField(default=False)),
                ('consent_research', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical patient',
                'verbose_name_plural': 'historical patients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('national_id', core.encrypted_fields.EncryptedCharField(blank=True, max_length=64)),
                ('national_id_lookup', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=150)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age_estimated', models.BooleanField(default=False)),
                ('phone_number', core.encrypted_fields.EncryptedCharField(blank=True, max_length=32)),
                ('phone_number_lookup', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('village', models.CharField(blank=True, max_length=150)),
                ('traditional_authority', models.CharField(blank=True, max_length=150)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, choices=[('northern', 'Northern'), ('central', 'Central'), ('southern', 'Southern')], max_length=10)),
                ('occupation_or_school', models.CharField(blank=True, max_length=150)),
                ('patient_category', models.CharField(choices=[('outpatient', 'Outpatient'), ('inpatient', 'Inpatient'), ('student', 'Student'), ('staff', 'Staff'), ('private', 'Private'), ('referred', 'Referred'), ('emergency', 'Emergency'), ('research', 'Research participant')], default='outpatient', max_length=20)),
                ('consent_care', models.BooleanField(default=True)),
                ('consent_teaching', models.BooleanField(default=False)),
                ('consent_research', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients_registered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=100)),
                ('phone_number', core.encrypted_fields.EncryptedCharField(blank=True, max_length=32)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DuplicateConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('candidate_patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='patients.patient')),
                ('new_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_confirmations', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMergeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('merged_at', models.DateTimeField(auto_now_add=True)),
                ('duplicate_patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merged_into', to='patients.patient')),
                ('merged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('primary_patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merged_from', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='patients.patient')),
            ],
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name'], name='patients_pa_last_na_1b32a7_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['patient_number'], name='patients_pa_patient_f07fc4_idx'),
        ),
    ]
