# Generated by Django 5.2.15 on 2026-07-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='consent_data_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='consent_data_use',
            field=models.BooleanField(default=False),
        ),
    ]
