# Generated by Django 5.2.15 on 2026-07-03 21:33

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
    ]
