# Generated by Django 5.2.15 on 2026-07-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_pg_trgm_extension'),
        ('patients', '0003_historicalnextofkin'),
    ]

    operations = [
    ]
