# Generated by Django 5.2.15 on 2026-07-03 23:04

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CKDDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('stage_1', 'Stage 1 (eGFR ≥ 90)'), ('stage_2', 'Stage 2 (eGFR 60–89)'), ('stage_3a', 'Stage 3a (eGFR 45–59)'), ('stage_3b', 'Stage 3b (eGFR 30–44)'), ('stage_4', 'Stage 4 (eGFR 15–29)'), ('stage_5', 'Stage 5 (eGFR < 15)')], max_length=10)),
                ('diagnosed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('diagnosed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ckd_diagnoses', to='patients.patient')),
            ],
            options={
                'ordering': ['-diagnosed_at'],
            },
        ),
        migrations.CreateModel(
            name='DialysisPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_per_week', models.PositiveIntegerField()),
                ('target_fluid_removal_l', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('vascular_access', models.CharField(choices=[('av_fistula', 'AV Fistula'), ('av_graft', 'AV Graft'), ('tunneled_catheter', 'Tunneled Catheter'), ('temporary_catheter', 'Temporary Catheter'), ('peritoneal', 'Peritoneal')], default='av_fistula', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dialysis_prescriptions', to='patients.patient')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DialysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('pre_weight_kg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('post_weight_kg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fluid_removed_l', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('complications', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='dialysis.dialysisprescription')),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCKDDiagnosis',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('stage', models.CharField(choices=[('stage_1', 'Stage 1 (eGFR ≥ 90)'), ('stage_2', 'Stage 2 (eGFR 60–89)'), ('stage_3a', 'Stage 3a (eGFR 45–59)'), ('stage_3b', 'Stage 3b (eGFR 30–44)'), ('stage_4', 'Stage 4 (eGFR 15–29)'), ('stage_5', 'Stage 5 (eGFR < 15)')], max_length=10)),
                ('diagnosed_at', models.DateTimeField(blank=True, editable=False)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('diagnosed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient')),
            ],
            options={
                'verbose_name': 'historical ckd diagnosis',
                'verbose_name_plural': 'historical ckd diagnosiss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDialysisPrescription',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('frequency_per_week', models.PositiveIntegerField()),
                ('target_fluid_removal_l', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('vascular_access', models.CharField(choices=[('av_fistula', 'AV Fistula'), ('av_graft', 'AV Graft'), ('tunneled_catheter', 'Tunneled Catheter'), ('temporary_catheter', 'Temporary Catheter'), ('peritoneal', 'Peritoneal')], default='av_fistula', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient')),
                ('prescribed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical dialysis prescription',
                'verbose_name_plural': 'historical dialysis prescriptions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDialysisSession',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('pre_weight_kg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('post_weight_kg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fluid_removed_l', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('complications', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('conducted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dialysis.dialysisprescription')),
            ],
            options={
                'verbose_name': 'historical dialysis session',
                'verbose_name_plural': 'historical dialysis sessions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
